import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      <img src='logo.jpg'></img>
        
        <h1 className={styles.title}>
          CLEAR MEN <a href="https://nextjs.org"> ANTICASPA </a>
        </h1>

        <p>CLEAR é expert nos cuidados com o couro cabeludo e no tratamento da caspa, realizando constantes investimentos em tecnologia e pesquisas com o consumidor. Esses diferenciais fazem de CLEAR a principal marca do mercado anticaspa brasileiro líder do segmento. Sua exclusiva e avançada tecnologia, atua no combate à caspa desde a primeira lavagem. Sua fórmula com vitaminas e minerais, atua profundamente no couro cabeludo e cabelo, prevenindo sintomas como coceira, quebra e ressecamento, proporcionando fios saudáveis e bonitos. A marca possui em seu portfólio linhas desenvolvidas para homens e mulheres.</p>

       

        <div className={styles.grid}>
          <a href="./contato" className={styles.card}>
            <h2> Contato &rarr;</h2>
            <p> Acesse aqui. </p>
          </a>

          <a href="./produtos" className={styles.card}>
            <h2> NOSSOS PRODUTOS  &rarr;</h2>
            <p> Acesse aqui.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
